### ISSUE TITLE
Git仓库更新检查执行推送时报错

### ISSUE THREAD

**Issue by YuapXc** [KaguyaJs/Yunzai-DF-Plugin#10]
近期Git仓库更新检查执行推送时报错，如图
![df报错](https://github.com/user-attachments/assets/8a6af25f-1f90-4963-81f8-35881699f847)
已配置推送群组，且刚开始使用的时候是正常的

**Comment by DenFengLai** [comment]
配置文件中的Group必须是一个数组，而不是直接填写群号，格式如下
```yaml
# 推送的群聊列表
Gruop: 
 - 12345
 - 67890
```
