### ISSUE TITLE
Git仓库更新检查定时任务出现：请指定 group_id 或 user_id

### ISSUE THREAD

**Issue by Sakura1618** [KaguyaJs/Yunzai-DF-Plugin#11]
环境：
**TRSS Yunzai** 与 **DF-Plugin** 均为最新版本
**LLOneBot v3.29.5**

配置：
![code1](https://github.com/user-attachments/assets/6af484fb-a178-4a6f-8155-01fc1d45834b)

报错：
![code](https://github.com/user-attachments/assets/c0eedf73-5f1a-44e9-8f8a-a67b147de523)

补充：
Git仓库更新检查 - 定时任务 稳定触发。
使用 `#检查仓库更新` 手动检查不会出现该问题，可以正常发送图片。

**Comment by DenFengLai** [comment]
拼写错误
![image](https://github.com/user-attachments/assets/600d4336-277d-43ac-a9c7-ed6fce8df93e)
