### ISSUE TITLE
[问题反馈]: 使用#DF安装图库后仍调用XY-api获取图片

### ISSUE THREAD

**Issue by scaking4** [KaguyaJs/Yunzai-DF-Plugin#14]
### 反馈内容

使用#DF安装图库后仍调用XY-api获取图片

### 其他说明

constants/Path.js 
export const Res_Path = `${Plugin_Path}/resources`
export const Poke_Path = `${Res_Path}/resources/poke`（是不是多了个resources，
改成export const Poke_Path = `${Res_Path}/poke`是不是就可以用本地图库了）

**Comment by DenFengLai** [comment]
是的，很抱歉这是由于我的疏忽大意导致的，我预计会在今晚找机会修复，为您带来不便。
